name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tensorflow-gpu=2.6.0
  - pandas=1.3.4
  - numpy=1.19.5
  - jupyter=1.0.0
  - dask=2021.11.2
  - tensorboard=2.7.0
  - pillow=8.4.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.3
  - keras-tuner=1.0.3