name: match
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter==1.0.0
  - matplotlib==3.4.3
  - seaborn==0.11.2
  - flask==1.1.2
  - pandas==1.3.4
  - tqdm==4.62.3
  - gunicorn==20.1.0
  - xgboost==1.5.0
